apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: my-rest-api-358-auth
  namespace: my-rest-api
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: my-rest-api-358
  rules:
    authentication:
      "api-key-users":
        apiKey:
          selector:
            matchLabels:
              app: my-rest-api-358
          allNamespaces: true
        credentials:
          authorizationHeader:
            prefix: APIKEY
        when:
          - selector: request.url_path
            operator: matches
            value: "^/api/v1/.*"
      "public-paths":
        anonymous: {}
        when:
          - selector: request.url_path
            operator: matches
            value: "^/health$|^/openapi\\.json$|^/docs.*"