apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: my-rest-api-358-binding
  namespace: my-rest-api
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.clone_url)
  - name: git-revision
    value: $(body.after)
